### ISSUE TITLE
Feature request: run pnpm with old version node

### ISSUE THREAD

**Issue by chengcyber** [pnpm/action-setup#18]
### What

This is a feature request to this action supports run pnpm@6 in node@10 environment.

### Why

I use pnpm@6 in local dev, but my package wants to support `node>=10`, which break the rule of pnpm@6, engines.node >=12.

### Detail

add a parameter (maybe named `compiled_install`),
If true, instead of install pnpm directly, run sth like `curl -f https://get.pnpm.io/v6.js | node - add --global pnpm` to setup a compiled pnpm binary as `pnpm` CLI

**Comment by KSXGitHub** [comment]
`pnpm` itself requires Node.js >= 12.17, as seen [here](https://github.com/pnpm/pnpm/releases/tag/v6.0.0):

> Node.js v10 support is dropped. At least Node.js v12.17 is required for the package to work

So I think this issue is more suitable at [pnpm/pnpm](https://github.com/pnpm/pnpm). But before that, consider workaround: Bundling pnpm@6 with node 12.17 into a self-contained binary.

**Comment by zkochan** [comment]
We can do this easily by installing [@pnpm/exe](https://www.npmjs.com/package/@pnpm/exe) instead of [pnpm](https://www.npmjs.com/package/pnpm). However, `@pnpm/exe` is only available since v6.17.1. So this will be a breaking change. But I think it is OK to do this breaking change since it will make pnpm work with older Node.js versions.
